import {
  type LucideIcon,
  Users,
  Shield,
  Settings,
  LayoutDashboard,
  BarChart2,
  FileText,
  Bell,
  Lock,
  Briefcase,
  Package,
  ShoppingCart,
  CreditCard,
  Truck,
  Wrench,
  Globe,
  Database,
  Mail,
  Calendar,
  Tag,
  Map,
  HelpCircle,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  users: Users,
  user: Users,
  shield: Shield,
  roles: Shield,
  settings: Settings,
  config: Settings,
  dashboard: LayoutDashboard,
  home: LayoutDashboard,
  analytics: BarChart2,
  reports: BarChart2,
  'bar-chart': BarChart2,
  documents: FileText,
  files: FileText,
  'file-text': FileText,
  notifications: Bell,
  bell: Bell,
  security: Lock,
  lock: Lock,
  briefcase: Briefcase,
  projects: Briefcase,
  inventory: Package,
  products: Package,
  package: Package,
  orders: ShoppingCart,
  cart: ShoppingCart,
  billing: CreditCard,
  payments: CreditCard,
  shipping: Truck,
  logistics: Truck,
  maintenance: Wrench,
  tools: Wrench,
  website: Globe,
  web: Globe,
  database: Database,
  data: Database,
  mail: Mail,
  email: Mail,
  calendar: Calendar,
  schedule: Calendar,
  tags: Tag,
  categories: Tag,
  map: Map,
  locations: Map,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name?.toLowerCase()] ?? HelpCircle;
}
